name: Rust

on:
  push:
    branches: [ "develop.vm" ]
  pull_request:
    branches: [ "develop.vm" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dioxus-cli
      run: cargo install dioxus-cli --version "0.7.10" --locked
    # - name: Run tests
    #   run: cargo test --verbose
    - name: Build
      run: cargo xtask build --profile release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: moddl
        path: dist/release/

