name: Rust

on:
  push:
    branches: [ "develop.vm" ]
  pull_request:
    branches: [ "develop.vm" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    # - name: Run tests
    #   run: cargo test --verbose
    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
        name: moddl
        path: |
          target/release/moddl.exe
          target/release/portaudio_x64.dll
          target/release/builtins/
          
